system:
  port: 8080

mysql:
  host: "10.0.5.11"
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db-name: "136_holdon"
  username: "root"
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100

jwt:
  signing-key: "deepseek"
  expires-time: 7200    # 单位：秒
  buffer-time: 3600     # 缓冲时间，单位：秒
  issuer: "hextech" 