definitions:
  api.RegisterRequest:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: test_user
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /user/info:
    get:
      description: 获取当前登录用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取用户信息
      tags:
      - 用户接口
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - 用户接口
  /user/register:
    post:
      consumes:
      - application/json
      description: 新用户注册接口
      parameters:
      - description: 注册信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 用户注册
      tags:
      - 用户接口
swagger: "2.0"
